# Generated by Django 5.2.7 on 2025-11-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('event', 'Event'), ('task', 'Task'), ('reminder', 'Reminder')], default='event', max_length=10),
        ),
    ]
